### ISSUE TITLE
Optional "Updated" date

### ISSUE THREAD

**Issue by JPSPLeite** [gsilano/EuropeCV#10]
This issue is similar to:
https://github.com/gsilano/EuropeCV/issues/4

The feature that writes the update date at the top of the CV is not optional. It should be optional since sometimes one doesn't want future employers to know the last time the CV was updated.
My manual workaround was to edit the europecv.cls file, commenting line 420, the one that calls for the date to be written.

To make the feature optional, line 420 can simply be wrapped in a IF controlled by a global option but, unfortunately, I lack the skills to do it.

**Comment by gsilano** [comment]
The CV update date has been made optional. Please, take a look at the documentation by viewing the `\ecvdate{}` command.
