### ISSUE TITLE
Serious forward compatibility problems

### ISSUE THREAD

**Issue by jspitz** [gsilano/EuropeCV#2]
The recent release of europecv.cls introduced unnecessary forward compatibility problems

1. by adding a second mandatory argument to `\ecvtelephone`. Old documents now fail to compile with

> Runaway argument?
> ! Paragraph ended before \ecvtelephone was complete

It's probably too late now, but this problem could have been circumvented by making the new phone number a second optional argument (or using keyval). But note that the documentation needs updating.

2. by silently dropping `\ecvfax` which results in LaTeX errors of old documents as well

3. by renaming `\ecvsection` without introducing a backwards compatibility alias (`\let\ecvsection\section`)

All these changes make it hard to maintain documents. Particularly, as a LyX developer, I am quite at a loss regarding the question how we can keep up maintenance of this class for LyX, since our layout files should work for users who still use TeXLive 2017 and older distributions as well.

**Comment by gsilano** [comment]
First of all, I would like to say thank you for opening this issue. I have just updated the EuropeCV LaTeX package. As you can see in the CHANGELOG file, now the `\ecvsection` (together with the new feature `\section`) and `\ecvfax` commands have been restored. Furthermore, the documentation has been updated to better explain the new changes and how to use them.

Please, download the new CTAN package release.

**Comment by jspitz** [comment]
Thank you for the quick action! It would be perfect (in terms of compatibility) if you could make the office number argument of `\ecvtelephone` optional, as argued in the OP.

**Comment by gsilano** [comment]
I did it :)

**Comment by jspitz** [comment]
Hm, but not yet in the repo. I see
`\ecvtelephone[mobile]{private}{office}`
rather than
`\ecvtelephone[mobile][office]{private}`
Note the two **optional** argument.
This would be 100% forward compatible with older documents (though not backwards compatible, but that's impossible with new features).

Code-wise, that would mean something such as (untested):
```
\def\ecvtelephone{%
   \@ifnextchar[%
     {\ecvtelephone@i}
     {\ecvtelephone@i[]}%
}
\def\ecvtelephone@i[#1]{%
   \@ifnextchar[%
     {\ecvtelephone@ii{#1}}
     {\ecvtelephone@ii{#1}[]}%
}
\def\ecvtelephone@ii#1[#2]#3{%
 \def\ecv@mobile{#1}
 \def\ecv@office{#2}
 \def\ecv@telephone{#3}
}
```

**Comment by gsilano** [comment]
Hmm! You're right. Currently, I have not enough time to work on it. It would be nice if you could open a pull to fix the issue.

**Comment by jspitz** [comment]
Done. I also fixed some other issues I encountered. See commit log.
