### ISSUE TITLE
Insert tiled in urls

### ISSUE THREAD

**Issue by DPDmancul** [gsilano/EuropeCV#22]
If I insert a tilde (`~`) in the homepage url:
`\ecvhomepage{https://www.dei.unipd.it/~peressonid}`
it is treated like a nbsp and so not showed: `https://www.dei.unipd.it/ peressonid` which address to: `https://www.dei.unipd.it/%5Cprotect %5Cunhbox %5Cvoidb@x %5Cprotect %5Cpenalty %5C@M %5C %7B%7Dperessonid`.

If I escape it with `\~{}` (`\ecvhomepage{https://www.dei.unipd.it/\~{}peressonid}`) the following error is raised:
```
! Incompatible list can't be unboxed.
\SOUL@analyze ->{\setbox \z@ \vbox {\unvcopy \z@ 
                                                 \unskip \unpenalty \global ...
l.24   \end
           {europasscv}
? 
```

I managed to get the right address using url escape: `\ecvhomepage{https://www.dei.unipd.it/\%7Eperessonid}`, but the output is ugly.

**Comment by gsilano** [comment]
Hi @DPDmancul! I addressed your problem, and it works for me. I mean, I have no compilation errors and the website is linked correctly. Below, is the code I used in the `cv_template_academic_en.tex` file (see the `templates` folder) for the test.

```
\ecvname{Name, Surname}
\ecvfootername{Name, Surname}
\ecvaddress[(Remove if not relevant)][(Remove if not relevant)]{(Remove if not relevant)}
\ecvtelephone[(Remove if not relevant)][(Remove if not relevant)]{(Remove if not relevant)}
\ecvfax{(Remove if not relevant)}
\ecvemail{\href{mailto:email@gemail.com}{email@email.com}}
\ecvprofessional{\href{mailto:email@email.it}{email@email.it}}
\ecvpec{\href{mailto:emailo@pec.it}{email@pec.it}}
\ecvhomepage{\url{https://www.dei.unipd.it/~peressonid}}
\ecvmatrixriot{(Remove if not relevant)}
\ecvskype{(Remove if not relevant)}
\ecvnationality{(Remove if not relevant)}
\ecvdateofbirth{(Remove if not relevant)}
\ecvgender{(Remove if not relevant)}
\ecvdate{\today}
\ecvyoutube{\url{www.youtube.com/myChannel}} 
%\ecvpicture[width=3cm]{mypicture}
%\ecvfootnote{For further details please take a look here: \url{http://europass.cedefop.eu.int}\\
%\textcopyright~European Communities, 2003.}
```

Please, check it out and let me know if the problem still persists.

**HERE IS THE LINK TO DOWNLOAD THE PDF FILE:** [cv_template_academic_en.pdf](https://github.com/gsilano/EuropeCV/files/5415593/cv_template_academic_en.pdf)

**Comment by DPDmancul** [comment]
Solved the problem thank you!
