### ISSUE TITLE
I think (?) EuropeCV will fail when new LaTeX2e is released

### ISSUE THREAD

**Issue by scottkosty** [gsilano/EuropeCV#29]
Thank you very much for your work on this package, Giuseppe, and for taking over after Nicola's work!

First, I should say I don't know much about LaTeX, so my notes below could be incorrect.

LaTeX2e is [going to release](https://www.latex-project.org//news/2022/05/27/latex-dev-2022-2/) a new version in a few days. TeX Live kindly provides a way to easily test the upcoming release: instead of using `pdflatex` (or friends), we can use `pdflatex-dev`. The following simple example succeeds when using `pdflatex` but fails with `pdflatex-dev` on an updated TeX Live 2022 system:

```
\documentclass[nologo]{europecv}

\begin{document}

\begin{europecv}{}

\ecvpersonalinfo{}{}

\end{europecv}{}

\end{document}
```

Here is the log file: [mwe.log](https://github.com/gsilano/EuropeCV/files/8824585/mwe.log)

From what I understand, this might be happening because europecv.cls uses `\RequirePackage{hyperref}` inside `\AtBeginDocument`. It is suggested [here](https://github.com/latex3/hyperref/issues/242#issuecomment-1144116033) that:

> In general it's a bad idea, hence dangerous, to load any package with \AtBeginDocument. Whether such use case works or not totally depends on the implementation of package and I doubt if it's ever officially supported.

As for why this is an issue only with the upcoming release and not the current release, I'm not sure but it might be described by the [most recent](https://www.latex-project.org/news/latex2e-news/ltnews35.pdf) LaTeX News issue (see the part about "Fixed bug when setting hook rules for one-time hooks").

**Comment by scottkosty** [comment]
> Thanks for opening your first issue here! Make sure that no other issues on the same topic have already been opened!

Thanks. I did search before opening, and I didn't find any issue about hooks or hyperref or the upcoming LaTeX release.

**Comment by scottkosty** [comment]
I think the explanations at the upstream [#841](https://github.com/latex3/latex2e/issues/841) are helpful for understanding how to fix this issue in EuropeCV.

**Comment by gsilano** [comment]
Hi @scottkosty! Thank you for the nice words and for taking care to check the source of this problem. This is a very busy time for me, would you mind fixing the bug by opening a pull request on EuropeCV? Afterwards, I will manage the transfer on CTAN.

**Comment by scottkosty** [comment]
@gsilano Thanks for the reply! I don't know much LaTeX. I tried a few hacks and nothing worked. I then just asked for help at https://tex.stackexchange.com/questions/646747/europecv-fails-with-latex2e-pre-release-because-of-loading-hyperref-in-atbegind. Hopefully we can get this fixed before the new LaTeX2e release lands.

<blockquote><img src="https://cdn.sstatic.net/Sites/tex/Img/apple-touch-icon@2.png?v=eaf26b461720" width="48" align="right"><div>TeX - LaTeX Stack Exchange</div><div><strong><a href="https://tex.stackexchange.com/questions/646747/europecv-fails-with-latex2e-pre-release-because-of-loading-hyperref-in-atbegind">EuropeCV fails with LaTeX2e pre-release because of loading hyperref in \AtBeginDocument</a></strong></div><div>Below is a minimal example that compiles successfully with stable TeX Live 2022 pdflatex but fails with the latest (and expected to be released in a couple days I think) pdflatex-dev:
\documentclass[</div></blockquote>

**Comment by davidcarlisle** [comment]
https://github.com/latex3/hyperref/issues/242#issuecomment-1146813792
