### ISSUE TITLE
`europasslogo.pdf` does not work with XeTeX

### ISSUE THREAD

**Issue by vlasakm** [gsilano/EuropeCV#31]
The file `europasslogo.pdf` has incorrect offsets, which prevents it from being read by more strict programs, like `dvipdfmx` (used internally by XeTeX). Hence the following fails:

```tex
% test.tex
\XeTeXpdffile {europasslogo.pdf} width \hsize \relax

\bye
```

```
$ xetex test.tex
This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xetex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
! Unable to load picture or PDF file 'europasslogo.pdf'.
<to be read again>
                   \relax
l.2 ...file {europasslogo.pdf} width \hsize \relax

? h
The requested image couldn't be read because
it was not a recognized image format.

?
```

Note that after I ask for help with `h` the error is more specific, but not completely correct.

The issue is that in the PDF file the offsets to PDF objects are all wrong by a couple of bytes. I didn't investigate whether this is because of incorrect handling of binary data or end of lines or something else.

`mutool` or `qpdf` can be used to fix the issue. E.g. this invocation of `mutool` keeps most of the human readability of the PDF file. My output attached for reference.

```
mutool clean -d europasslogo.pdf europasslogo.pdf
```

The issue may be present in more files, but I found this thanks to @llde's original report here: https://github.com/tectonic-typesetting/tectonic/issues/921.

I am fairly sure that https://github.com/gsilano/EuropeCV/pull/27/commits/3fe8f1996f92314a96f675b9913474b4e5c74f1c from https://github.com/gsilano/EuropeCV/pull/27 is essentially the same issue - the PDF file could be _found_, but not _processed_. Hence I think that unspecifying the extension would allow PS centric workflows to use `.eps` file and PDF centric workflows use `.pdf` file directly. (Currently e.g. when running XeTeX each run the `.eps` file is converted using ghostscript to PDF, because XeTeX can't process `.eps` files directly.)

Below is my suggestion for the fix, but its largely untested (because of the `begindocument` sorting rule error) and not thorough (maybe the same issue is in other files, I didn't check).

```diff
diff --git a/europasslogo.pdf b/europasslogo.pdf
index 53f1721..61b6cd8 100644
--- a/europasslogo.pdf
+++ b/europasslogo.pdf
@@ -1314,15 +1314,15 @@ endobj
 xref
 0 10
 0000000000 65535 f
-0000033487 00000 n
-0000000016 00000 n
-0000033281 00000 n
-0000033347 00000 n
-0000033632 00000 n
-0000033567 00000 n
-0000033594 00000 n
-0000033715 00000 n
-0000033846 00000 n
+0000033485 00000 n
+0000000015 00000 n
+0000033279 00000 n
+0000033345 00000 n
+0000033630 00000 n
+0000033565 00000 n
+0000033592 00000 n
+0000033713 00000 n
+0000033844 00000 n
 trailer
 <<
 /Size 10
@@ -1331,5 +1331,5 @@ trailer
 /ID [<5bb2a8ac5de76fd7a41a0d69aa22822b><5bb2a8ac5de76fd7a41a0d69aa22822b>]
 >>
 startxref
-33913
+33911
 %%EOF
diff --git a/europecv.cls b/europecv.cls
index 0b84e54..d8b52c7 100644
--- a/europecv.cls
+++ b/europecv.cls
@@ -261,7 +261,7 @@
 % Europass logo
 \DeclareOption{logo}{%
 \providecommand*\draweuropasslogo{%
-   \includegraphics[width=\ecv@logowidth]{europasslogo.eps}}
+   \includegraphics[width=\ecv@logowidth]{europasslogo}}
 }
 \DeclareOption{nologo}{\renewcommand*\draweuropasslogo{}}

```

**Comment by gsilano** [comment]
Hi! Thanks for having opened this issue and for having found a solution for the problem raised in #27. Then, if I got it well, using the command `mutool clean -d europasslogo.pdf europasslogo.pdf` should fix the issue. Right?
If so, just replace the PDF in the repository. Is that correct?

**Comment by vlasakm** [comment]
To be precise:

`mutool clean -d europasslogo.pdf europasslogo.pdf` should fix the PDF file.

But the PDF file will not be used by the `europecv` class, since it now explicitly requests the EPS file.

To use the newly fixed PDF file, revert of https://github.com/gsilano/EuropeCV/pull/27/commits/3fe8f1996f92314a96f675b9913474b4e5c74f1c is required. I.e. the following:

```diff
diff --git a/europecv.cls b/europecv.cls
index 0b84e54..d8b52c7 100644
--- a/europecv.cls
+++ b/europecv.cls
@@ -261,7 +261,7 @@
 % Europass logo
 \DeclareOption{logo}{%
 \providecommand*\draweuropasslogo{%
-   \includegraphics[width=\ecv@logowidth]{europasslogo.eps}}
+   \includegraphics[width=\ecv@logowidth]{europasslogo}}
 }
 \DeclareOption{nologo}{\renewcommand*\draweuropasslogo{}}
```

The current state works, https://github.com/tectonic-typesetting/tectonic/issues/921 is actually what #27 fixed, it's just that an old version of the package gets used there (01/03/2020). So #27 works, but this is IMO a better fix.

**Comment by gsilano** [comment]
I see your point. Perhaps, it is best to leave things as they are if everything works out well. In the event that someone is having trouble with this problem, your solution may be what they are looking for. What do you think?

**Comment by vlasakm** [comment]
Sure, if that works for you.
