### ISSUE TITLE
don't need "updated ..." - line

### ISSUE THREAD

**Issue by dg2meu** [gsilano/EuropeCV#4]
I used your template "cv_template_en.tex". 
I don't need the "Updated <date>" line at the beginning of the pdf (see picture). How can I delete this?
![dont_need_updated](https://user-images.githubusercontent.com/42391554/44119445-7ccf2bee-a019-11e8-9c54-fffcfd87fc69.png)

I tried to change the "ecvde.def"-file (in my CV german version).
Original:
  \def\ecv@date{\ecv@utf{Aktualisiert auf \today}}
My changes:
  \def\ecv@date{}

After that, sure "Updated <date>" is not shown. But there is a big gap.
![without_updated](https://user-images.githubusercontent.com/42391554/44119643-246dbd52-a01a-11e8-8332-4a32ee43720c.png)

I then changed the .tex-file:
  \begin{europecv}	
  \vspace{-4cm}
  \ecvpersonalinfo[20pt]
  \ecvitem{\large\textbf{Desired employment/ Occupational~field}}{\large\textbf{(Remove if not relevant)}}

But the gap is still to big...

**Comment by gsilano** [comment]
Hi @dg2meu!! I'm glad to hear you say that the LaTeX _europecv_ package is useful for you. About your issue, you should remove:

- the 419th and 420th line into the _europecv.cls_ file,
- the 7th line into the _ecvde.def_ file.

However, you should bear in mind that when you go to write a CV in English, the _ecven.def_ file should also be modified in according to that of _ecvde.def_.

**Comment by gsilano** [comment]
The CV update date has been made optional. Please, take a look at the documentation by viewing the `\ecvdate{}` command.
