### ISSUE TITLE
only mobile number

### ISSUE THREAD

**Issue by dg2meu** [gsilano/EuropeCV#5]
I used your template "cv_template_en.tex".
I only have a mobile number, no normal telefone-number. Up to now I used the "telephone"-definition for my mobile phone number.
I like your changes. It would be nice to only define a mobile number:
![mobile_number](https://user-images.githubusercontent.com/42391554/44120004-3cb42b5c-a01b-11e8-8cd2-bcf6402e06d8.png)

Is this possible?

**Comment by gsilano** [comment]
Below you find a possible go around. Please, insert in the `.tex` file your mobile phone number as reported below:

`\ecvtelephone{XXX/YYY}`

Then, edit the definition into the _ecvde.def_ file, tenth line, replacing _Telefon_ with _Mobil_. Should be fine!!
