### ISSUE TITLE
Getting data from DB

### ISSUE THREAD

**Issue by pcav** [gsilano/EuropeCV#8]
It would be interesting using your template while getting data from a DB. We have all our data in PostgreSQL, in principle it should be feasible.

**Comment by gsilano** [comment]
Hi @pcav,

this is a good idea. Other users may find it useful for their own purposes. In any case, I have no idea how it should be done. I have never worked in LaTeX with this type of applications. Could you tell me something more? Have you already used it?

**Comment by pcav** [comment]
Done, with a Python script. Now polishing, Will be made public on https://gitlab.com/faunalia/cv-scripts
Thanks.

<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/users/sign_in">Sign in</a></strong></div><div>GitLab.com</div></blockquote>

**Comment by gsilano** [comment]
@pcav, first of all, thanks for your contributions. Unfortunately, the provided link is not available. Please, could you provide the code via a pull request? Of course, at any time you will the owner of the code and you will able to decide on its life. Likewise, some lines in the README.md file would make the developed code useful for all the EuropeCV users.

**Comment by pcav** [comment]
Yes, the code is still private, we have to clean it up. Will make it public ASAP.

**Comment by gsilano** [comment]
Great!! :100: We await your news :smiley:

**Comment by pcav** [comment]
https://gitlab.com/faunalia/cv_pg_generator
please note: we are currently using https://github.com/gmazzamuto/europasscv, not this one, sorry :)

<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/faunalia/cv_pg_generator">faunalia / cv_pg_generator</a></strong></div><div>GitLab.com</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/18688794?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/gmazzamuto/europasscv">gmazzamuto/europasscv</a></strong></div><div>Unofficial LATEX class for the new version of the Europass curriculum vitae - gmazzamuto/europasscv</div></blockquote>

**Comment by gsilano** [comment]
Take it easy!! I'm very happy to hear you say that there is an alternative solution to create your own CV in LaTeX is available. Thanks for sharing :-)
